---

- name: install fxa-customs-server
  tags: code
  sudo: true
  sudo_user: app
  git: repo={{ customs_git_repo }}
       dest=/data/fxa-customs-server
       version={{ customs_git_version }}
       force=true
  notify:
    - install fxa-customs-server dependencies
    - restart fxa-customs-server

- name: supervise fxa-customs-server
  sudo: true
  copy: src=fxa-customs-server.conf dest=/etc/supervisor.d/fxa-customs-server.conf
  notify: update supervisor

- name: configure fxa-customs-server
  sudo: true
  sudo_user: app
  template: src=config.json.j2 dest=/data/fxa-customs-server/config/stage.json
  notify: restart fxa-customs-server

- meta: flush_handlers
