---
- name: Start redis server docker container
  become: true
  docker_container:
    # See note in https://github.com/mozilla/fxa-dev/tree/docker#about-using-docker_container-and-semi-mandatory-quoting
    name: redis
    image: redis{{ ':' + redis_docker_tag }}
    state: "{{ redis_docker_state }}"
    network_mode: host
    ports:
      - 6379:6379
    command: redis-server
  register: container

- debug: var=container

- meta: flush_handlers
