---
- name: Copy repo file into place
  copy: src=datadog.repo dest=/etc/yum.repos.d/datadog.repo owner=root group=root mode=0644
  sudo: true

- name: Install datadog-agent package
  yum: name=datadog-agent state=latest
  sudo: true

- template: src=datadog.conf.j2 dest=/etc/dd-agent/datadog.conf
  notify: restart datadog
  sudo: true

# use command not service to workaround; fixed in ansible 2.x maybe
# https://github.com/ansible/ansible-modules-core/issues/1298
- name: start datadog-agent
  command: service datadog-agent start
  sudo: true
