---

- name: install fxa-rp-untrusted dependencies
  sudo: true
  sudo_user: app
  command: npm install --production chdir=/data/fxa-rp-untrusted

- name: gen preverified token keypair
  sudo: true
  sudo_user: app
  command: node /data/fxa-rp-untrusted/scripts/gen_keys.js chdir=/data/fxa-rp-untrusted

- name: restart fxa-rp-untrusted
  sudo: true
  supervisorctl: name=fxa-rp-untrusted state=restarted
