---

- name: install fxa-rp-untrusted dependencies
  sudo: true
  sudo_user: app
  command: npm install --production chdir=/data/fxa-rp-untrusted

- name: restart fxa-rp-untrusted
  sudo: true
  supervisorctl: name=fxa-rp-untrusted state=restarted
