---

- name: create fxa-auth-db-server heka decoder
  sudo: true
  copy: src=fxa_auth_db_server.lua dest=/usr/share/heka/lua_decoders/fxa_auth_db_server.lua
  notify: restart heka

- name: configure heka
  sudo: true
  template: src=heka.toml.j2 dest=/etc/heka.d/fxa-auth-db-server.toml
  notify: restart heka

- name: install fxa-auth-db-server
  tags: code
  sudo: true
  sudo_user: app
  git: repo={{ authdb_git_repo }}
       dest=/data/fxa-auth-db-server
       version={{ authdb_git_version }}
       force=true
  notify:
    - install fxa-auth-db-server dependencies
    - run db patcher
    - restart fxa-auth-db-server

- name: configure fxa-auth-db-server
  sudo: true
  sudo_user: app
  template: src=config.json.j2 dest=/data/fxa-auth-db-server/config/stage.json
  notify: restart fxa-auth-db-server

- name: supervise fxa-auth-db-server
  sudo: true
  copy: src=fxa-auth-db-server.conf dest=/etc/supervisor.d/fxa-auth-db-server.conf
  notify: update supervisor

- meta: flush_handlers
