---

- name: install fxa-rp dependencies
  sudo: true
  sudo_user: app
  command: npm install --production chdir=/data/fxa-rp

- name: gen preverified token keypair
  sudo: true
  sudo_user: app
  command: node /data/fxa-rp/scripts/gen_keys.js chdir=/data/fxa-rp

- name: restart fxa-rp
  sudo: true
  supervisorctl: name=fxa-rp state=restarted
