---

- name: gather all facts
  remote_user: vagrant
  hosts: all

- hosts: db
  gather_facts: false
  remote_user: vagrant
  roles:
    - db

- hosts: content
  gather_facts: false
  remote_user: vagrant
  roles:
    - content

- hosts: customs
  gather_facts: false
  remote_user: vagrant
  roles:
    - customs

- hosts: auth
  gather_facts: false
  remote_user: vagrant
  roles:
    - auth

- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: add entries to /etc/hosts
      sudo: true
      lineinfile: dest=/etc/hosts regexp="{{ item.regexp }}" line="{{ item.line }}"
      with_items:
        - { regexp: " fxa.local$", line: '{{ hostvars["content"]["ansible_default_ipv4"]["address"] }} fxa.local'}
        - { regexp: " api.fxa.local$", line: '{{ hostvars["auth"]["ansible_default_ipv4"]["address"] }} api.fxa.local'}
