---

- name: install fxa-notification-server
  tags: code
  sudo: true
  sudo_user: app
  git: repo={{ notification_git_repo }}
       dest=/data/fxa-notification-server
       version={{ notification_git_version }}
       force=true
  notify: #so meta
    - install fxa-notification-server dependencies
    - restart fxa-notification-server

- name: install json tool
  sudo: true
  npm: name=json global=yes

- name: find redis
  shell: 'aws elasticache describe-cache-clusters --cache-cluster-id {{ redis_id }} --region {{ region }} --show-cache-node-info | json CacheClusters[0].CacheNodes[0].Endpoint.Address'
  changed_when: false
  register: redis_host

- name: configure fxa-notification-server
  sudo: true
  sudo_user: app
  template: src=config.json.j2 dest=/data/fxa-notification-server/config.json
  notify: restart fxa-notification-server

- name: create keys
  sudo: true
  sudo_user: app
  script: generate_keys.sh creates=/data/fxa-notification-server/secret.pem

- name: supervise fxa-notification-server
  sudo: true
  copy: src=fxa-notification-server.conf dest=/etc/supervisor.d/fxa-notification-server.conf
  notify: update supervisor

- meta: flush_handlers
