---

- name: install cronie
  sudo: true
  yum: name=cronie state=present

- name: start crond
  sudo: true
  service: name=crond state=started enabled=true

- name: install ansible
  sudo: true
  pip: name=ansible version=1.6.1 state=present

- name: install fxa-dev
  sudo: true
  git: repo=https://github.com/dannycoates/fxa-dev.git
       dest=/data/fxa-dev
       version=master
       force=true

- name: disable requiretty in /etc/sudoers
  sudo: true
  lineinfile: dest=/etc/sudoers state=absent regexp='Defaults\s+requiretty' validate='visudo -cf %s'

- name: copy my_vars.yml
  sudo: true
  copy: src=../../../aws/my_vars.yml dest=/data/fxa-dev/aws/my_vars.yml

# TODO make the permissions non-ec2 specific
- file: path=/var/log/ansible state=directory owner=ec2-user group=ec2-user
  sudo: true

# TODO the job should be a shell script that can try to recover from errors
- name: cron update
  cron: name="fxa update"
        minute=*/10
        job="cd /data/fxa-dev/aws; ansible-playbook -i localhost, local.yml > /var/log/ansible/update.log"
