---

- hosts: default
  remote_user: vagrant
  vars:
    public_protocol: http
    domain_name: fxa.local
  roles:
    - email
    - mysql
    - memcached
    - authdb
    - content
    - customs
    - auth
    - oauth
    - profile
    - rp
    - log

- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: add entries to /etc/hosts
      sudo: true
      lineinfile: dest=/etc/hosts regexp="{{ item.regexp }}" line="{{ item.line }}"
      with_items:
        - { regexp: " fxa.local$", line: '{{ hostvars["default"]["ansible_all_ipv4_addresses"][hostvars["default"]["iface"]] }} fxa.local'}
        - { regexp: " 123done-fxa.local$", line: '{{ hostvars["default"]["ansible_all_ipv4_addresses"][hostvars["default"]["iface"]] }} 123done-fxa.local'}
        - { regexp: " oauth-fxa.local$", line: '{{ hostvars["default"]["ansible_all_ipv4_addresses"][hostvars["default"]["iface"]] }} oauth-fxa.local'}
