---

- name: configure nginx upstream
  become: true
  template: src=upstream.conf.j2 dest=/etc/nginx/conf.d/upstream/http_channelserver.conf
  notify: reload nginx config

- name: configure nginx location
  become: true
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/location/http_channelserver.conf
  notify: reload nginx config

- name: Pull channelserver docker image
  become: true
  docker_image:
    state: present
    name: mozilla/pairsona
    tag: "{{ channelserver_docker_tag }}"
  register: image

- debug: var=image

- name: Create directory for downloading geolocation database
  file: path=/data/config/channelserver/mmdb state=directory owner=app group=app mode=0775
  become: true

- name: Download geolocation database
  become: true
  get_url:
    url: http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
    dest: /data/config/channelserver/mmdb/GeoLite2-City.tar.gz

- name: Unzip geolocation database
  become: true
  unarchive:
    src: /data/config/channelserver/mmdb/GeoLite2-City.tar.gz
    dest: /data/config/channelserver/mmdb
    remote_src: yes

- name: Symlink geolocation database
  become: true
  shell: ln -sf `ls -1ad --color=never GeoLite2-City_*|tail -1` latest
  args:
    chdir: /data/config/channelserver/mmdb

- name: Start channelserver container
  become: true
  docker_container:
    name: channelserver
    image: mozilla/pairsona{{ ':' + channelserver_docker_tag }}
    state: "{{ channelserver_docker_state }}"
    ports:
      - 8058:8058
    env:
      PAIR_HOSTNAME: "0.0.0.0"
      PAIR_PORT: "8058"
      PAIR_MMDB_LOC: "/config/mmdb/latest/GeoLite2-City.mmdb"
      PAIR_DEBUG: "true"
      PAIR_VERBOSE: "true"
      RUST_BACKTRACE: "1"
    volumes:
      - /data/config/channelserver:/config
  register: container

- debug: var=container
