---

- name: postmap sasl_passwd
  become: true
  command: /usr/sbin/postmap /etc/postfix/sasl_passwd

- name: set MTA to postfix
  become: true
  # the alternatives module isn't working
  # alternatives: name=mta path=/usr/sbin/sendmail.postfix
  command: alternatives --set mta /usr/sbin/sendmail.postfix

- name: reload postfix
  become: true
  service: name=postfix state=reloaded

