---

- name: configure nginx upstream
  become: true
  template: src=upstream.conf.j2 dest=/etc/nginx/conf.d/upstream/http_fxa-rp-untrusted.conf
  notify: reload nginx config

- name: create shared mount point for configuration info
  file: path=/data/config/rp-untrusted state=directory owner=app group=app mode=0777
  become: true

- name: configure fxa-rp
  become: true
  become_user: app
  template: src=config.json.j2 dest=/data/config/rp-untrusted/config-dev.json

# Relies on the rp-build role to create the mozilla/123done image.

# Note: container renamed to `rp2-untrusted` so that existing fxa-dev boxes
# will remove the currently running container named `rp-untrusted` and
# `rp2-untrusted` will not fail to bind on the listening tcp port number.

- name: Ensure removal of existing `rp-untrusted` container.
  become: true
  docker_container:
    name: rp-untrusted
    state: absent

- name: Start 123done docker container as rp2-untrusted
  become: true
  docker_container:
    name: rp2-untrusted
    image: mozilla/123done{{ ':' + rp_docker_tag }}
    state: "{{ rp_docker_state }}"
    network_mode: host
    ports:
      - 4902:4902
    command: node ./server.js
    env:
      CONFIG_123DONE: "/config/config-dev.json"
    volumes:
      - /data/config/rp-untrusted:/config
  register: container

- debug: var=container

- meta: flush_handlers
