---

- name: set MTA to postfix
  sudo: true
  # the alternatives module isn't working
  # alternatives: name=mta path=/usr/sbin/sendmail.postfix
  command: alternatives --set mta /usr/sbin/sendmail.postfix
