---

- name: install able dependencies
  sudo: true
  sudo_user: app
  npm: path=/data/able

- name: build js bundle
  sudo: true
  sudo_user: app
  command: npm run bundle chdir=/data/able

- name: restart able
  sudo: true
  supervisorctl: name=able state=restarted

