---

- name: install human tools
  become: true
  yum:
    name: "{{ item }}"
    state: present
    use_backend: yum
  with_items:
    - emacs-nox
    - strace
    - lsof
    - tmux
    - htop
    - mysql

- name: get team public keys
  git: repo=https://github.com/mozilla/identity-pubkeys.git
       dest=/data/identity-pubkeys
       version=abbef3b82c6f954d2fca9e1c23cfd9f5f9a94596
       force=true
  notify: update authorized_keys
