---

- name: install human tools
  become: true
  yum: name={{ item }} state=present
  with_items:
    - emacs-nox
    - strace
    - lsof
    - tmux
    - htop
    - mysql

- name: get team public keys
  git: repo=https://github.com/mozilla/identity-pubkeys.git
       dest=/data/identity-pubkeys
       version=ecf2768d7c3d834731dc1f802b0640193293aaa3
       force=true
  notify: update authorized_keys
