---

- name: install human tools
  sudo: true
  yum: name={{ item }} state=present
  with_items:
    - emacs-nox
    - strace
    - lsof
    - tmux
    - htop
    - mysql

- name: get team public keys
  git: repo=https://github.com/mozilla/identity-pubkeys.git
       dest=/data/identity-pubkeys
       version=faf11d61fdc166004c134b75587d059734f5bdb1
       force=true
  notify: update authorized_keys
