---

- name: install human tools
  become: true
  yum: name={{ item }} state=present
  with_items:
    - emacs-nox
    - strace
    - lsof
    - tmux
    - htop
    - mysql

- name: get team public keys
  git: repo=https://github.com/mozilla/identity-pubkeys.git
       dest=/data/identity-pubkeys
       version=aa1da19d2bace3bf6784bf43bfcbf68bf60d52ca
       force=true
  notify: update authorized_keys
