---

- name: install human tools
  sudo: true
  yum: name={{ item }} state=present
  with_items:
    - emacs-nox
    - strace
    - lsof
    - tmux
    - htop

- name: get team public keys
  git: repo=https://github.com/mozilla/identity-pubkeys.git
       dest=/data/identity-pubkeys
       version=05af279f784385bfa4dfda785d7609d1588809d3
       force=true
  notify: update authorized_keys
