---

- name: install gmp-devel
  sudo: true
  yum: name=gmp-devel state=present

- name: install nginx
  sudo: true
  yum: name=nginx state=present enablerepo=mozilla-services-aws

- name: configure nginx
  sudo: true
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: start nginx
  sudo: true
  service: name=nginx state=started enabled=true

# postfix should be temporary

- name: install postfix
  sudo: true
  yum: name=postfix state=present

- name: start postfix
  sudo: true
  service: name=postfix state=started enabled=true

- name: install fxa-auth-server
  git: repo=https://github.com/dannycoates/picl-idp.git
       dest=/data/fxa-auth-server
       version={{ fxa_auth_server_version | default("master") }}
  notify:
    - install fxa-auth-server dependencies
    - gen dev key-pair
    - restart fxa-auth-server

- name: configure fxa-auth-server
  template: src=config.json.j2 dest=/data/fxa-auth-server/config/prod.json
  notify: restart fxa-auth-server

- name: supervise fxa-auth-server
  sudo: true
  copy: src=fxa-auth-server.conf dest=/etc/supervisor.d/fxa-auth-server.conf
  notify: restart supervisor
