---

- name: install gmp-devel
  sudo: true
  yum: name=gmp-devel state=present

- name: configure nginx upstream
  sudo: true
  template: src=upstream.conf.j2 dest=/etc/nginx/conf.d/upstream/http_fxa_auth.conf
  notify: reload nginx config

- name: configure nginx location
  sudo: true
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/location/http_fxa_auth.conf
  notify: reload nginx config

- name: install fxa-auth-server
  tags: code
  sudo: true
  sudo_user: app
  git: repo={{ auth_git_repo }}
       dest=/data/fxa-auth-server
       version={{ auth_git_version }}
       force=true
  notify:
    - install fxa-auth-server dependencies
    - gen dev key-pair
    - restart fxa-auth-server

- name: configure fxa-auth-server
  sudo: true
  sudo_user: app
  template: src=config.json.j2 dest=/data/fxa-auth-server/config/stage.json
  notify: restart fxa-auth-server

- name: supervise fxa-auth-server
  sudo: true
  copy: src=fxa-auth-server.conf dest=/etc/supervisor.d/fxa-auth-server.conf
  notify: update supervisor

- meta: flush_handlers
