---

- name: ensure /home/ec2-user/docker-gc
  file: path=/home/ec2-user/docker-gc state=directory owner=ec2-user group=ec2-user

- name: ensure /home/ec2-user/docker-gc/run
  file: path=/home/ec2-user/docker-gc/run state=directory owner=ec2-user group=ec2-user

- name: configure docker-gc
  copy: src={{ item }} dest=/home/ec2-user/docker-gc/ mode='u+rwx'
  with_items:
    - docker-gc
    - docker-gc-exclude
    - docker-gc-exclude-containers
    - run-docker-gc

# offset by 5 minutes from ansible */10 update job
- name: cron update docker-gc
  cron: name="docker-gc"
        weekday='*'
        month='*'
        day='*'
        hour='*'
        minute='5,15,25,35,45,55'
        job="/home/ec2-user/docker-gc/run-docker-gc >> /var/log/ansible/docker-gc.log"

- meta: flush_handlers
