---

- name: install gmp-devel
  sudo: true
  yum: name=gmp-devel state=present

- name: configure nginx upstream
  sudo: true
  template: src=upstream.conf.j2 dest=/etc/nginx/conf.d/upstream/http_fxa_content.conf
  notify: reload nginx config

- name: configure nginx location
  sudo: true
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/location/http_fxa_content.conf
  notify: reload nginx config

- name: install nonsense
  sudo: true
  npm: name={{ item }} global=yes state=present
  with_items:
    - bower
    - grunt-cli

- name: install fxa-content-server
  tags: code
  sudo: true
  sudo_user: app
  git: repo={{ content_git_repo }}
       dest=/data/fxa-content-server
       version={{ content_git_version }}
       force=true
  notify:
    - install fxa-content-server dependencies
    - build fxa-content-server assets
    - restart fxa-content-server
    - restart fxa-basket-proxy
    - restart fxa-null-basket

- name: configure fxa-content-server
  sudo: true
  sudo_user: app
  template: src=config.json.j2 dest=/data/fxa-content-server/server/config/local.json
  notify:
    - restart fxa-content-server
    - restart fxa-basket-proxy
    - restart fxa-null-basket

- name: supervise fxa-content-server
  sudo: true
  copy: src=fxa-content-server.conf dest=/etc/supervisor.d/fxa-content-server.conf
  notify: update supervisor

- name: supervise fxa-basket-proxy
  sudo: true
  copy: src=fxa-basket-proxy.conf dest=/etc/supervisor.d/fxa-basket-proxy.conf
  notify: update supervisor

- name: supervise fxa-null-basket
  sudo: true
  copy: src=fxa-null-basket.conf dest=/etc/supervisor.d/fxa-null-basket.conf
  notify: update supervisor

- meta: flush_handlers
