---

- name: install gmp-devel
  sudo: true
  yum: name=gmp-devel state=present

- name: configure nginx
  sudo: true
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/http_fxa_content.conf
  notify: reload nginx config

- name: install nonsense
  sudo: true
  npm: name={{ item }} global=yes state=present
  with_items:
    - bower
    - grunt-cli
    - phantomjs

- name: install fxa-content-server
  tags: code
  sudo: true
  sudo_user: app
  git: repo={{ content_git_repo }}
       dest=/data/fxa-content-server
       version={{ content_git_version }}
  notify:
    - install fxa-content-server dependencies
    - build fxa-content-server assets
    - restart fxa-content-server

- name: configure fxa-content-server
  sudo: true
  sudo_user: app
  template: src=config.json.j2 dest=/data/fxa-content-server/server/config/local.json
  notify: restart fxa-content-server

- name: supervise fxa-content-server
  sudo: true
  copy: src=fxa-content-server.conf dest=/etc/supervisor.d/fxa-content-server.conf
  notify: update supervisor
