---

- name: build 123done docker image
  become: true
  docker_image:
    state: present
    force: true
    path: /data/123done
    name: mozilla/123done
    tag: "{{ rp_docker_tag }}"
  register: image

- debug: var=image
