---

- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - my_vars.yml
  tasks:
    - name: create key pair
      local_action:
        module: ec2_key
        name: "{{ key_name }}"
        region: "{{ region }}"
        key_material: "{{ item }}"
      with_file: ~/.ssh/id_rsa.pub

    - name: create basic stack
      action: cloudformation
        stack_name="{{ stack_name }}-fxadev"
        state=present
        region="{{ region }}"
        template=cloudformation/basic.json
      args:
        template_parameters:
          KeyName: "{{ key_name }}"
          HostedZone: "{{ hosted_zone }}"
          StackName: "{{ stack_name }}"
      register: stack

    - debug: var=stack

    - name: add new host
      add_host: hostname={{ stack['stack_outputs']['Instance'] }} groupname=whatevs

- name: Configure instance
  hosts: whatevs
  remote_user: ec2-user
  gather_facts: true
  vars_files:
    - my_vars.yml
  vars:
    content_server_url: 'http://{{ stack_name }}.{{ hosted_zone }}'
    auth_server_url: 'http://{{ stack_name }}.{{ hosted_zone }}:81'
    auth_public_url: 'http://{{ stack_name }}.{{ hosted_zone }}:81'
  roles:
    - common
    - mysql
    - memcached
    - authdb
    - content
    - customs
    - auth
    - log
