---

- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "defaults.yml"
    - "environments/{{ stack_name }}.yml"
  vars:
    key_name: "{{ stack_name }}-fxadev"
    config_name: "{{ stack_name }}"
  tasks:
    - name: check that chosen remote branch exists (did you push?). Aborts if not.
      command: git rev-parse origin/"{{ fxadev_git_version }}"
      
    - name: generate (optional) RDS password
      shell: openssl rand -hex 16
      register: rds_password

    - name: create key pair
      local_action:
        module: ec2_key
        name: "{{ key_name }}"
        region: "{{ region }}"
        key_material: "{{ item }}"
      with_file: ~/.ssh/id_rsa.pub

    - name: create basic stack (this should take ~5 minutes)
      action: cloudformation
        stack_name="{{ stack_name }}-fxadev"
        state=present
        region="{{ region }}"
        template=cloudformation/moz-single.json
      args:
        template_parameters:
          KeyName: "{{ key_name }}"
          ConfigName: "{{ config_name }}"
          BranchName: "{{ fxadev_git_version }}"
          HostedZone: "{{ hosted_zone }}"
          Subdomain: "{{ subdomain }}"
          RDSPassword: "{{ rds_password.stdout }}"
          UseRDS: "{{ use_rds | default('false') }}"
          SSLCertificateArn: "{{ ssl_certificate_arn }}"
          EC2InstanceType: "{{ ec2_instance_type }}"
          EC2VolumeSize: "{{ ec2_volume_size | to_json }}"
        tags:
          Owner: "{{ owner | default('nobody@mozilla.com') }}"
          REAPER_SPARE_ME: "{{ reaper_spare_me | default('false') }}"
      register: stack

    - debug: var=stack

    - name: Wait for nginx on the instance to come online (ignore FAILED RETRYING log messages)
      uri:
        url: "http://meta-{{ stack['stack_outputs']['ContentHost'] }}:1443/50x.html"
        follow_redirects: none
        status_code:
          - -1
          - 200
          - 404
      register: response
      until: response and response.get('status') != -1
      retries: 40 # 10 mins
      delay: 15

    - name: Check that the FxA services are returning a plausible `/__version__` (ignore FAILED RETRYING log messages)
      uri:
        url="{{ item.host }}"
        return_content=yes
        follow_redirects=none
      ignore_errors: yes # guard against early phase failure of DNS lookup or TCP connection
      register: response
      until: response and response.get('json') and response.get('json')['version'] is defined
      retries: 40 # 10 mins
      delay: 15
      with_items:
        # auth-server will start first, followed by content, RPs, oauth, profile
        - host: "https://{{ stack['stack_outputs']['ContentHost'] }}/auth/__version__"
        - host: "https://{{ stack['stack_outputs']['ContentHost'] }}/__version__"
        - host: "https://oauth-{{ stack['stack_outputs']['ContentHost'] }}/__version__"
        - host: "https://{{ stack['stack_outputs']['ContentHost'] }}/profile/__version__"

    - name: Assert that there are four responses from above
      assert:
        that: "(response.results | length) == 4"

    - name: Assert that each response has returned a version correctly
      assert:
        that: item['version'] is defined
      with_items: "{{ response.results | json_query('[][json]') }}"

    - debug: msg="{{ (response.results | json_query('[][json]')) }}"
