---

- name: Configure instance
  hosts: localhost
  connection: local
  vars_files:
    - my_vars.yml
  roles:
    - ses
    - mysql
    - memcached
    - authdb
    - content
    - customs
    - auth
    - log
    - cron_update
    - team
