---

- name: Configure instance
  hosts: localhost
  connection: local
  vars_files:
    - my_vars.yml
  vars:
    content_server_url: 'http://{{ stack_name }}.{{ hosted_zone }}'
    auth_server_url: 'http://{{ stack_name }}.{{ hosted_zone }}:81'
    auth_public_url: 'http://{{ stack_name }}.{{ hosted_zone }}:81'
  roles:
    - email
    - mysql
    - memcached
    - authdb
    - content
    - customs
    - auth
    - log
  tasks:
    - name: get s3 secrets
      sudo: true
      sudo_user: app
      s3: bucket=net.mozaws.ops.hiera-secrets
          object=common.yaml
          dest=/data/common.yml
          mode=get
