---

- name: Configure instance
  hosts: localhost
  connection: local
  vars_files:
    - my_vars.yml
  vars:
    content_server_url: 'https://{{ subdomain }}.{{ hosted_zone }}'
    auth_server_url: 'https://{{ subdomain }}.{{ hosted_zone }}:4443'
    auth_public_url: 'https://{{ subdomain }}.{{ hosted_zone }}:4443'
  roles:
    - ses
    - mysql
    - memcached
    - authdb
    - content
    - customs
    - auth
    - log
    - cron_update
