---

- name: no sendmail
  become: true
  yum: name=sendmail state=absent

- name: install postfix
  become: true
  yum: name=postfix state=present
  notify: set MTA to postfix

- name: install postfix main.cf
  become: true
  template:
    src=main.cf.j2
    dest=/etc/postfix/main.cf
    owner=root group=root mode=0644
  notify: reload postfix

- name: start postfix
  become: true
  service: name=postfix state=started enabled=true

# fedora 20 doesn't include rsyslog by default
- name: install rsyslog
  become: true
  yum: name=rsyslog state=present

- name: start rsyslog
  become: true
  service: name=rsyslog state=started enabled=true

# workaround for python/boto suckage with dotted bucket names
# https://github.com/boto/boto/issues/2836. Fixed in Ansible > 1.9.
- name: ensure boto.s3 uses OrdinaryCallingFormat()
  become: true
  ini_file: dest=/etc/boto.cfg
     state=present
     section=s3
     option=calling_format
     value=boto.s3.connection.OrdinaryCallingFormat
     owner=root
     mode=0644


- meta: flush_handlers
