---

- name: install fxa-auth-db-server dependencies
  sudo: true
  sudo_user: app
  npm: path=/data/fxa-auth-db-server production=true

- name: run db patcher
  sudo: true
  sudo_user: app
  command: node /data/fxa-auth-db-server/bin/db_patcher.js

- name: restart fxa-auth-db-server
  sudo: true
  supervisorctl: name=fxa-auth-db-server state=restarted
