---

- name: install fxa-auth-db-server dependencies
  sudo: true
  sudo_user: app
  npm: path=/data/fxa-auth-db-server production=true

- name: run db patcher
  sudo: true
  sudo_user: app
  command: node bin/db_patcher.js chdir=/data/fxa-auth-db-server

- name: restart fxa-auth-db-server
  sudo: true
  supervisorctl: name=fxa-auth-db-server state=restarted
