---

- name: install fxa-kv-server dependencies
  sudo: true
  sudo_user: app
  npm: path=/data/fxa-kv-server production=true

- name: restart fxa-kv-server
  sudo: true
  supervisorctl: name=fxa-kv-server state=restarted
