---

- name: install nginx
  become: true
  yum:
    name: nginx
    state: present
    use_backend: yum

- name: ensure /etc/nginx/conf.d/upstream directory
  file: path=/etc/nginx/conf.d/upstream state=directory
  become: true

- name: ensure /etc/nginx/conf.d/location directory 
  file: path=/etc/nginx/conf.d/location state=directory
  become: true

- name: delete nginx default.conf
  become: true
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: copy base nginx.conf
  become: true
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: reload nginx config

- name: start nginx
  become: true
  service: name=nginx state=started enabled=true
