---

- name: configure nginx
  sudo: true
  template: src=upstream.conf.j2 dest=/etc/nginx/conf.d/upstream/http_fxa_openid.conf
  notify: reload nginx config

- name: configure nginx location
  sudo: true
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/location/http_fxa_openid.conf
  notify: reload nginx config

- name: install fxa-openid-bridge
  tags: code
  sudo: true
  sudo_user: app
  git: repo={{ openid_git_repo }}
       dest=/data/fxa-openid-bridge
       version={{ openid_git_version }}
       force=true
  notify:
    - install fxa-openid-bridge dependencies
    - restart fxa-openid-bridge

- name: configure fxa-openid-bridge
  sudo: true
  sudo_user: app
  template: src=config.json.j2 dest=/data/fxa-openid-bridge/config.json
  notify: restart fxa-openid-bridge

- name: supervise fxa-openid-bridge
  sudo: true
  copy: src=fxa-openid-bridge.conf dest=/etc/supervisor.d/fxa-openid-bridge.conf
  notify: update supervisor

- meta: flush_handlers
