---

# To avoid breaking tests by clobbering `dist` from underneath the running
# content server, we copy the current working directory to a temporary
# location, do the npm and grunt changes in the copy, and then swap the copy
# into place (and restart).

# there shouldn't be anything leftover but just in case
- name: begin install fxa-content-server by removing any leftover in /var/tmp
  sudo: true
  sudo_user: app
  command: rm -rf /var/tmp/fxa-content-server

- name: begin install fxa-content-server dependencies with a copy
  sudo: true
  sudo_user: app
  command: cp -rpf /data/fxa-content-server /var/tmp

- name: install fxa-content-server dependencies 
  sudo: true
  sudo_user: app
  command: npm install --production chdir=/var/tmp/fxa-content-server

- name: build fxa-content-server assets
  sudo: true
  sudo_user: app
  command: grunt build chdir=/var/tmp/fxa-content-server

- name: remove original /data/fxa-content-server
  sudo: true
  sudo_user: app
  command: rm -rf /data/fxa-content-server

- name: move updated fxa-content-server back into /data
  sudo: true
  sudo_user: app
  command: mv /var/tmp/fxa-content-server /data

- name: restart fxa-content-server
  sudo: true
  supervisorctl: name=fxa-content-server state=restarted
