---

- name: install memcached
  become: true
  yum:
    name: memcached
    state: present
    use_backend: yum

- name: start memcached
  become: true
  service: name=memcached state=started enabled=true
