---
public_protocol: https
private_protocol: http
domain_name: "{{ subdomain }}.{{ hosted_zone }}"
content_public_url: "{{ public_protocol }}://{{ domain_name }}"
auth_mailer_git_repo: https://github.com/mozilla/fxa-auth-mailer.git
auth_mailer_git_version: master
auth_mailer_port: 10136
auth_mailer_smtp_host: 127.0.0.1
auth_mailer_smtp_port: 25
auth_mailer_sender: "Firefox Accounts <verification@{{ domain_name }}>"
auth_mailer_verify_url: "{{ content_public_url }}/v1/verify_email"
auth_mailer_recovery_url: "{{ content_public_url }}/v1/complete_reset_password"
